"""add session_id to conversations

Revision ID: 74c96d1e3c53
Revises: 2f0515e290d8
Create Date: 2026-05-25 11:43:01.504192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c96d1e3c53'
down_revision: Union[str, Sequence[str], None] = '2f0515e290d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('session_id', sa.Text(), nullable=True))
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_column('conversations', 'session_id')
    # ### end Alembic commands ###
